using static FlawlessChips.Flawless2A03.NodeIds;

namespace FlawlessChips.Tests;

public class Flawless2A03Tests
{
    [Test]
    public async Task TestStartupStateMatchesVisual2A03()
    {
        var chip = new Flawless2A03();

        // This state was retrieved from Visual 2A03 by running the equivalent simulation,
        // and then calling the JavaScript getState() function to get the state.
        await Assert.That(chip.GetState()).IsEqualTo(
            "llllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxllllllllllllllllllllllllllllxllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllxllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxxllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllxlxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllllllllllllllllxlllllllllllllllllllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvgxxlllllllllllllllllxxxxxxxxlllllllllxxxxxllllllllllllllllxxxlxxxxlxxxxxxxxllxllllllllxlxxllxlxxlllxxxxlxxxxxlxlxxxxlxxxxllxxxlxxllxllllllllxxxxxllllllllllllllllllxllxxllxxxlxlllllllllllxxllllllllxxlllllllxxxxxxlllllllxxlxllllllllllllllllxxxxxllllllllxxxlllllllllllxlllllllxxxxxxllxlxlxxxxxxllllxlxxxxxllxllllllllxxxllxllxxxxxlllllxxllllllxlllllllllxllllxxlllllxxllxxlxllllxlllllxllllllllxxxxlllllxxxllxlllllllllllxlxllxxllllllllllllllxlllllxxllllxllllllllllxxlxxxllllxxllllxxlxlllllllxxlllxlllllllllllllllllllllllllxxllllxlxlllxlxllxllxxxllxlxllllxxlxxxllxllxlxlxllllxlxllxxxllxlxlxlxxxxxlxxxxlxxxxllllxxxllxllllxlllllxxxlllllxlllllxxlxxxxxxllxxllllllllxlxlxllllllxxxlllxlllxxxxxxlllxllxllxxlxxxlxxxlxxxxxllxxxxlxxllxlxlxxlxxllxxxxxxxxxxxxxxlxxxxxlxxllxxlxllxxlllxxlxxxxxlxlxxlxxxxxxxxxxxxxxxlxxlxxxxxllxxxxxxlxxxxlxllxxlxxllxxxxxxxxxxxxlxxlllxxxxxxxxxxxxlxxxxxxxxxxxxxxxxxxxxxxxlxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlxlxxxxxxxxxxxxxxxxxxxxxlllxxxlllxlxxllxxlxlxxxxllxxxxxxxxxxlllxxxxlxxllxxlxllxlxxxxxllxlxllxxxxxxxxxxlxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlxlxxxxxxxxxxxxxxxxxxxxxxxxxxxxlxlllllllllllllllllxxlxllxlllxlxlllllllllllllxxlllllllllxxxxxxxlllxlxxxxxlxxlllllllllllxllxxxlllllllllllllllxlllxllxllllllllllxlllllllllxllllxxlxllxxllllxllxllllllxxxlxxxxxlllllllxxxxlllxxxxlxllxxlxllxxllllxlxxllllxlllllxlllxlxllxlllxlllxxxlllxxllxlllllllllllxlxllxlllllxllxllllllxlxlxllxlxllllxlllllllxxxlxxllxlllllllxllllllxxxxlllxllllxlxxxlxllxlxxxxllxlxxllllxxllxlxxlxxxllxlxxxxxxlxlllllllllxxllxlxlllllllxxxlxlxlxxlllxxxxlllllxllllxllllxxxllxlllllllxlxllxxxlllllxxxxlllxlllllxlllxllllllllxxlxllxxllxlllllxllxlxllxlxxxxxlxxlxlxxlxlllxlllllllxllxllxlxlxllllllllllllllllllllxllxlllxxxllllxlxlllllxlxxxxxlllxlxlxxxxxxllxxxlxxxxxxlxxxxxllxxxxxxxxllxxxxxxxlxxllxlxlxxxlxxxxlxlllllllxxxxxllxlxlxllxlllllxxxllxxxxxllllllxllxllxxxxllllxxxlllllllllxllllxllxxllllllllllllllxllllxllxxllllllllllllllxlllxllllxllllllllllllxlxlllllllllxlllllllllxllllxxlxxllllxxlxlllxxxllllllllllxlllxllllllxllllllllllllllllxllxxlllxlllllllllllllxllxlxllxllllllllllxxxxxxxxxxxxxxxxlxxxllxxxxxllllllxxxxxxxxxxxxxxxxxxxxxxxlllllllllllllllllllllllllllllllxxxxlllllxxxxllllllxxxxxxllllllllxllllllllllllllllllllxxxxllllllllllllllllxxllllllllllllllllxxlllxllxlllllxlxllxlxlllllxlllxxxxlllllllllllllxxlxllxlxllllxxxxxlxllllllllllxxllllxlxllxlxlllllxlllxxxxlllllllllxxlxllxlxllllxxxxxlllllllllllxxllllxlxllxlxlllllxlllxxxxxlllllllllxxxlxllxlxllllxxxxxlxllxlllllllxxlllllxllxxllxllllllxxxxllllllllxllxxllxlllllllxxxxxlllllllllllllllllllllllllxllllllllxllxlllllllxxlxxxxllllllllxllxlllllllllxxlxxlxxllllxxlxxlllllxllllxllxllllxxlllllllllllxllxlllllllxxxxxxllllllllllxxllllllllxllxlllxllllxxxxllllllllxxllxllxlllllllxxxxlllllllllllllllllllxlxllxlxllxlllllxxlllllllllxxllxxllllxxxxllllllllllxllllxllxxllllxllxxlllllllllllxxxllxlllllxxxxxlllllllllllllxlxllxlxlllxlllxxllllllllllllllllllllxxllxxllllllxxlxxlllllllllxxllllxlxllxlxlllllllxxlllllllllxxllxxllxxxxxlllllllllxllxlllllxxllllllxxlllxxllxxxxlllllllxxlllllxllxlxlxlllllxxlllllxlxxlxxxxxllllxxxxxxlxxlllllllxlxxlxlllllllllllllllxxxxxxxxllxxlxxlllllllxxlllllllllllllxlllllllllxxxxxxxxxxxxlxxlxlllxxxlllxxlxxlllllllllllllllllllllllllllllllllxxxxxxxxlxxxxlllllxxxxxlxxxlllxllxlxxxlllllllllllllxlllllllllllllllllllllllxxxxxxxxxxxxxxllxxlxxllxxxllllllllllllxllxlxlxlxlllxxllllxxllxllxxxllllllxxlxlllxxllxllllxllxlxxllxlxlllllllllxxxlxxlllllllllxlxlllxllllxllxlxlxlllxxxxlllxllllxllxllxllllxlxllllllllxxxlxxlllllllllxlxxlxlllllllllxxxlxlxlxxxxxlllllxxxxllllxlllxlllxlxlllllllllxxxxxlllllllxxlllxlllllxlxlxxllxlxxxxlllxlxllllllxlxlllxlxllllllllllxxxxxxllllllllxxllllllxllxlxlxxlxxlxllllllxllxllllllxlxlllllllxlxxlxxllllxlllllxxlllllllxlxlxllxxxxllllllllxlllxllxlxllllllllxxxxllllllllxlllllllllxlxlxxxxxlllllxlllllllxlxlllllllllxllxxllllllllxllxlllllllxlxlxxxxlllllllxxlllxllxllllllllllllxxxlllllxlllllxxlxllllllllxlxxxllxxlllllllllxlllllllllxllllxxllllllllllxlllllllxllxxxlllllllllllxllllllllllllxlxxlllllllxllllllllxlxlxlllxxlxlllllllxlllllllllllllllxxlllllxlllxlllllllllllxlxxlllxllllllllllxlllllllxllllllllxllllxxlllllllxlxlllxllllxllllxllllllxxlllxxllllxllxllllxllxllllxlxlxlllxlxllxllllllxlxlllllllllllllllllxxxxxlllxxllxxllllllxllxlllxllxlllxlllllxllllllllxlllxxlxxlllllllxllxllllxxlllxllllxlxxxllllllllllxlllxlxlxlllxllllxlllllllxlxllxlxllllxlxllllllllllllxxlxxllllxllllxlllllllxlllllxxxllxlxllllllxlllllllllxxxxxxxxxxxxxxlxxxxxlxxlxllxxllllllllllllllxxlxlxllxllllllxlllxllxxlxxllxxlllllxxlxxxllllllxxllxlxlxlxlllxxlxxllxlllxlxllllllllllxxlxllxllxxllllxlxlxlxllxxlxllllllxlllllllllxlllllxlxllxllxxxlxlxlllxlllxlxxxllxlxxlxllllllllxllxlxxxxxxxxlxlxllxxlxlllxxlxxxxxxxxllxlxlllxlxlxlxlxxlxxxxxxxxxlxxlllxxlxlllllxllllllllllllllllllxlllllxxxlxxxlxxxllllxxxxxllllxxxxxlxlxllxllllxlxxxxxxllxxxxxxlxllllxxxxxxxlxlxxxxllxlllllllllxlxxxxlxllllxxxxxxllllxxxxlllllxlllxlllllllllxlllllxlxxxxxlxllllxxxxxllllxxxxxxlllllxxlxllxlxllllllllxxlxxxxxxlxllllxxxllllxxxxxxlllllxlxxllxlxllllllllxxlxxxxxlxxllllxxxxllllxxxxxxllllxllllxlllllllllllllxxlxxlxlllllllllxxllxxxxxxlxllllxxxxllllxxxxxxllllxllxlxlxlxlllllllllxxxlxxxxxlxxllllxxxllllxxxxxllllxlxlxlxllllllllxxlxxxxxlxxllllxxxllllxxxxxxllllxxxxlllllllllxxxxxxxxllllllllxxxxxxxllllxxxxxlllllllllllllllxxxllllllllllllllllllllllllllllllllllllxxxxxlllllllllllllllllllllllllllllllllllxxxxxllllxxxxlllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxl");

        var memory = new byte[ushort.MaxValue + 1];

        var testProgram = new byte[]
        {
            0xa9, 0x00,              // LDA #$00
            0x20, 0x10, 0x00,        // JSR $0010
            0x4c, 0x02, 0x00,        // JMP $0002
            
            0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x40,
            
            0xe8,                    // INX
            0x88,                    // DEY
            0xe6, 0x0F,              // INC $0F
            0x38,                    // SEC
            0x69, 0x02,              // ADC #$02
            0x60                     // RTS
        };

        Array.Copy(testProgram, memory, testProgram.Length);

        chip.Startup();

        // This state was retrieved from Visual 2A03 by running the equivalent simulation,
        // and then calling the JavaScript getState() function to get the state.
        await Assert.That(chip.GetState()).IsEqualTo(
            "lllllhlllllhlhllhlhlllllhhhhhhxhlhhlhlhhlhlhhlhhllhhhlhhhhllllhllllhhllhllhhlllhlllhllhhlhhlhhhhlllhlhhhllhlhlhhlhhlhhlhllhlhllhhllllllllllhllhlxllllhhlllllllhhhllhllhlllhhhxllhlllllllhllllllllhhlhlhhllllllllllhhlhlhllllhhhllhhhhllhhllllhhllhllllllllllhllhlllllhhhllhlhlhllllhlhhhllhlhllllhxllhllhhllhlllhlllhlhllllhlllhlllhlllhllllllhlhlhhhllhhhlhllhllhlllhlhlhlhhhhlhlllhlhlhllhlhlhhlhlllhllllllhhllhlllllhhhlxlhlhllhhhhlllhllhhlllllllllllhhhlhllhhhhlhlllllhhlhhlhlhhlllhllhlhllhhlhhhhlhllhlhllhxhhhlllhlhllhllhhhhhllllhlhhlhhlhhlhllhhlhllhxlhllllllhlhlhhhxhhhhxlhhlhhlhhlllhhllllhlllllhlhhlhlhlhhllhhlhhllhhlllhllhhhhhhlllllhllllhllhhllhhhllhhhllllhlllhlxlhlhhlhlhllhhhlhllhllhhhlhhllllhhllhlhllhlllhhlhllhllhllllllhhlhhhhhhlhhlhhlllllhhlllllllllxlhhhlllhhllhlhllllhlllhlhllhlhhllllhllllhlhlllllllhlhhlhlhhllllhlhlllllhlhhlllhhlllhhhhhhhhhllhllllhhhlhhhlllllhlhlllhlhlhhlllllhlllllllllhhhlhhhhhhlllllllhhhxhlllhhxhlhhhhlhlhhhhlhllllllllhlllhlllhhhllhllhhllhllhllllllhlhlhhlhlllhhlhllhhlllhllhhlllllhlhlllhlhhlhlhhlhhllhhllhhhhlllllhlhhlhlhlhlhhhhhlhlhllllhlllhlhhllllhllhlllhhlhllhlllhhhhhlhhhhlllllllhhhhhlhllhlllhhlhhhhhhlxhhhhhhhlllhhlhhhhhhhllhlhhllhhhlhllllhhhllhhllhlllhlhlhhhlllhhhlhlhhhhlhlhlhlhlxxllhhlhlllhhhllllhlllhllllllhhhllhhlhhlhhlhlllhhhllllxhllhhlhllhlhhhlhlhhhhhhllhhhhllllllhhlhlhhllhhhhhlhhhhlxhhhlhhllhlllllhllhhllhhhlhllhhllhlhhllhhhhhxlxllhllllllllhlhhhhlllllhhllhhlhhllhlllhhlhhllhhlhlhhllhhllllhhhlhlllhllhhllhhhlhlhllhlhllllhhlhlllxhlhllllllhlhlhlhhhhlllhhlllhhlllhllllhhlhhlhhllhlhlhhlllhhlhhhlllhlhhllhlllhlhllhllllhhhllhlhhhhhlhllhllhhlllllllllhlllhllllhlhlhllllhllhlllhhlhhllhllllhllllhhllllllhhllllllhlhhlhhlhlhlllhhhllllhllllhlxlllhlhlllllhhlllhlhhllhlhlhllllllllllxlhllhlhllhllhhhhhhllllhxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvgxxhlhllllhhllhhhhhhxxxxxxxxhhlllllllxxxxxlhhhlhllhhhlhhllxxxlxxxxhxxxxxxxxllxllllllllxhxxhhxhxxlhlxxxxhxxxxxlxlxxxxhxxxxlhxxxlxxllxllhlhlhhxxxxxllllllhhllllllhhhhxllxxllxxxlxhhhhlhlhllhxxllllhhllxxhhhhllhxxxxxxhlhhlhhxxlxllhlhhlllhhhhlllxxxxxllhhlhhlxxxlllllhhllllxhhhhlllxxxxxxhhxhxhxxxxxxlhllxlxxxxxhhxllllllllxxxhhxllxxxxxhhllhxxllllllxlhhllhhhhxllllxxlllhhxxlhxxlxhhllxllhllxhhllllhhxxxxlhhhhxxxllxhhllhhhhllhxhxhhxxlllhhllhhhhhllxhhhhhxxllhhxlllhhhhllhxxlxxxhhhhxxhlllxxhxhllhhllxxhlhxlllhllhllllhlhlhhhhllhhhhxxhhhhxhxhhlxlxlhxlhxxxhhxhxllhhxxlxxxhhxhlxhxhxllllxlxllxxxhhxlxhxhxxxxxhxxxxhxxxxhhlhxxxllxhhhhxhllllxxxhhhhlxhhhhhxxlxxxxxxllxxlhlllhllxlxlxhlllhhxxxlllxhhhxxxxxxllhxllxhlxxlxxxhxxxhxxxxxllxxxxlxxhlxlxlxxhxxllxxxxxxxxxxxxxxhxxxxxhxxllxxhxhhxxhhlxxlxxxxxlxlxxlxxxxxxxxxxxxxxxhxxlxxxxxhhxxxxxxlxxxxlxllxxlxxlhxxxxxxxxxxxxhxxlhhxxxxxxxxxxxxhxxxxxxxxxxxxxxxxxxxxxxxlxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlxlxxxxxxxxxxxxxxxxxxxxxlllxxxhllxlxxhlxxlxhxxxxllxxxxxxxxxxhllxxxxlxxllxxlxhlxlxxxxxhlxlxhlxxxxxxxxxxlxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxlxhxxxxxxxxxxxxxxxxxxxxxxxxxxxxlxhllllhlllhlllhllhxxlxllxhhlxhxhllhllhhhlhlhxxlhlhlllllxxxxxxxhllxhxxxxxlxxhhlhlllhhhhxlhxxxlllllhhlllhhlhlxlllxlhxhllhhlhlhlxllhllhlllxhlhhxxlxhhxxhllhxhhxlhhhllxxxlxxxxxhlhlhhhxxxxlllxxxxlxhhxxlxlhxxhhhlxhxxlllhxlllhlxhhlxlxllxhhlxhllxxxhlhxxllxhhllllhhlhhxlxllxhhlllxhhxllllhhxlxlxlhxlxlhhhxlhlhhhlxxxlxxhlxllhlhhlxlhhhllxxxxhllxlhhhxlxxxlxhlxlxxxxhlxhxxllhlxxlhxhxxhxxxhlxlxxxxxxlxlhhhllllhxxhhxhxlhhllllxxxhxhxlxxlhlxxxxlhlhlxllllxhllhxxxllxlllllhlxlxhlxxxhllllxxxxhhlxlllhlxlhlxhllhllllxxlxhhxxllxlhlllxllxhxhhxhxxxxxhxxhxlxxhxlllxllhhlhhxlhxlhxlxlxllllllllllllllllhllhxhhxllhxxxllllxhxhlhlhxlxxxxxllhxlxlxxxxxxlhxxxlxxxxxxlxxxxxllxxxxxxxxllxxxxxxxlxxllxlxlxxxlxxxxlxhllllllxxxxxllxlxhxllxlllllxxxllxxxxxllllllxlhxlhxxxxllllxxxllhhhhhllxllhhxllxxhhhhllllhhhhhlxlllhxhhxxhhhhllllhhhhllxlhlxlllhxhhhllllhhhhlxlxhllllhhhhxllllhhhhlxlllhxxlxxlhlhxxhxhhhxxxllllhhhhhlxlhlxhlllllxhhhhhllllllhhhhlxlhxxlllxhhhhllllhhhhlxlhxhxllxhhhhhhlhhlxxxxxxxxxxxxxxxxlxxxlhxxxxxhllhllxxxxxxxxxxxxxxxxxxxxxxxlhlllllhlhllllllllllhllhhhlllllxxxxhhhlhxxxxlhhhhhxxxxxxhhlhllhlxhhllllllhhllhhllhlllxxxxlllhhlhhhlllhhllxxlhhlhlhllhlhlhhlxxhhlxllxlllllxhxhhxhxllllhxllhxxxxlhhhhhhlllhhlxxlxllxlxhhhhxxxxxlxlllllhllhlxxllllxhxhhxhxllllhxllhxxxxlhhlllhhlxxlxllxlxhhhhxxxxxllllllhllhlxxllllxhxhhxhxllllhxllhxxxxxlhhlllhhlxxxlxllxlxhhhhxxxxxlxllxllhllhlxxlllllxhhxxhhxllllllxxxxhhllllhhxllxxllxlhhhhlhxxxxxhhlhlhllhlhllhlhllhlhlhhhxllllllllxhhxllllhllxxhxxxxhhlhhlllxllxhhhlhhhhlxxlxxlxxllhhxxhxxllllhxllllxhhxllllxxlhhlhlhhlllxllxhhhhhhhxxxxxxhhhhllllllxxlllhllllxhhxllhxllllxxxxhhlllhhlxxhhxllxhhhhlllxxxxlhhhlllllllllllllllxhxhhxhxllxllllhxxhhhllllhhxxllxxhhhhxxxxllhllhllllxllllxhhxxhllhxllxxhhllhhllllhxxxllxhhhhhxxxxxllllllllhllllxhxhhxhxllhxlllxxhhllhhllhlhlhlhhlhlhxxllxxlhhlhhxxlxxlhlhhllllxxllllxhxhhxhxllllllhxxhhhllhhllxxllxxhhxxxxxllhhlllllxhhxllllhxxhllllhxxhllxxhhxxxxlllllllxxlhlllxhhxlxlxllhhhxxhhhllxlxxlxxxxxhlllxxxxxxlxxlllllllxhxxhxlllllllllhhhhllxxxxxxxxllxxhxxhllhlllxxlllllllllllhhxhhlhhhllhxxxxxxxxxxxxhxxhxlllxxxlllxxlxxlhhhlllhlhlhhlhlhllllllllllhhhhhhxxxxxxxxhxxxxhhllhxxxxxlxxxlhlxllxhxxxlhlhlhhlhlhllxlhlllllllllllhllllllllhxxxxxxxxxxxxxxhlxxlxxhlxxxhhllllllllllxlhxlxhxlxhlhxxhhllxxlhxhlxxxhhllllxxlxhhhxxlhxlhhhxhlxlxxllxhxhlhllllllxxxhxxllllllllhxlxlllxlhhhxhlxhxhxhhhxxxxlllxlhlhxhlxhhxllhhxhxllllllllxxxhxxlhhllllllxlxxlxlhhhhhhllxxxhxhxlxxxxxhhhllxxxxhhlhxlllxlhhxhxlhllllllhxxxxxlllllllxxlllxhhhhhxhxhxxllxhxxxxlllxhxhhlhlhxlxlhhxhxllllhlllllxxxxxxlhllllllxxllhhhlxlhxhxhxxlxxlxllhhlhxhlxhlllhlxhxlllllllxhxxlxxhhllxlllllxxllllhhhxhxhxhhxxxxllllhlhlxhhhxlhxlxlhllllhlxxxxllllllllxlllhhhhhhxhxhxxxxxlllllxhhhhlhhxhxllllllllhxllxxlllllllhxhlxhhhhhlhxhxlxxxxllhhllhxxhhlxhlxllllhllllhhlxxxhhhllxlllllxxlxlhhllhhhxhxxxhhxxlllllllllxllhhlllllxhhhhxxllllllllllxhhhhhhhxhhxxxllllllllllhxhhlhlllllhhhxlxxlllllhhxhlhlhlhhxhxhxlllxxlxllhhlhhxllllllllhlllhlhxxhhlllxhhlxhllllllllhhxhxxhlhxhhlllhlhllxlllhlhhxhlhlhlllxhllhxxlllhhllxhxlllxllhhxhlhhxlhllllxxllhxxhllhxllxhlllxhlxllhlxlxhxlllxhxhhxhllhhlxlxlhlhlhhlhlhlhhllhxxxxxlhlxxllxxllhhhlxlhxllhxhhxhllxhhhhlxllhlllhhxlhhxxhxxhhlhlhlxllxlllhxxlhlxhlhhxhxxxhhllhhllllxhhlxhxlxllhxhlhhxlhhhhllxlxhhxlxlhlhxlxlhhllhhllhhlxxlxxlhhhxhhhlxhlhhlhhxlllhlxxxlhxhxhllhhlxhlhhllllhxxxxxxxxxxxxxxlxxxxxlxxlxhlxxhlhlhlhhlhlhllxxhxlxhhxlhhlllxlhhxhhxxlxxhhxxllhhlxxlxxxlllhhlxxlhxhxlxlxlhhxxlxxlhxhllxhxhlhlhhhlhhxxhxllxllxxllhlxlxlxlxhhxxlxllhhhhxhlhlllhhhxhhhlhxlxlhxhlxxxhxlxlhhxllhxlxxxllxlxxhxlhhllhlhxhhxlxxxxxxxxhxhxllxxhxhllxxlxxxxxxxxhhxhxhhhxhxlxlxhxxlxxxxxxxxxhxxhhlxxlxhllllxlhllhlhlhhlhlhllllxlhhhhxxxlxxxlxxxhhhhxxxxxhhhhxxxxxhxhxhlxhhhhxlxxxxxxlhxxxxxxlxhhhhxxxxxxxhxhxxxxhlxlllllllllxhxxxxlxllllxxxxxxhhhhxxxxllllhxhhlxlllllllllxhllhlxlxxxxxlxllllxxxxxhhhhxxxxxxllllhxxhxhlxlxllllllllxxhxxxxxxlxllllxxxhhhhxxxxxxllllhxhxxhlxlxllllllllxxhxxxxxlxxllllxxxxhhhhxxxxxxllllxhlhlxhlhlhlhhlhlhlxxhxxlxlllllllllxxllxxxxxxlxllllxxxxhhhhxxxxxxllllxlhxhxhxlxlllllllllxxxhxxxxxlxxllllxxxhhhhxxxxxllllxhxhxlxllllllllxxhxxxxxlxxllllxxxhhhhxxxxxxllllxxxxllllllllhxxxxxxxxllllhhhhxxxxxxxllllxxxxxhlllhlhlhhlhlhlxxxllllllllhhhhllllhhhhllllllllhhhllhhhxxxxxhlllllhlllhhhhllllhhhhlllllhlllhhhhxxxxxhlllxxxxllllllllllhhllhlhlllllllllhhlhhhhlllllhllhlhllllllhhhhhlhlllllllllhhlhhhhhllllhllhlhllllllllllllhlhhlhllllllllllhhhhhhhllhlhhlhllllllllhlhhlhlllllllllhhhhhhhllhlhhlhlllllllllhlhhlhllllllllhhhhhhhhlhhlhlllllllhlhhlhllllllllhhhhhhhhlhhlhlllllllhllhlhlllllllhhhhhhhhhlhhlhlllllllllllhlhhlhllllllllhhhhhhhhlhhlhlllllllhlhllhllllllllllhhhhlhlhlhllhlllllllhllllhllllllllllhlhhlhhhllllhlllllllhhhllhhlllllllllhhlhhlhlhllllhllllllllhhllllllllllllllllllhlllhlhllllhlhhlllhlhllhlhlllhlllhllhhllhhllhllhllllllllllllllhlllllllhlhlllhlhllhlhhhlllllhllllhllllhllllhllllhllllhlllllhllllhlllllllllllllxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxh");

        var output = "";

        void HandleMemoryAccess()
        {
            if (chip.IsHigh(rw))
            {
                var address = chip.GetBus(ab);
                var data = memory[address];
                chip.SetBus(db, data);
            }
            else
            {
                var address = chip.GetBus(ab);
                var data = chip.GetBus(db);
                memory[address] = data;

                if (address == 0x000F)
                {
                    output += (char)data;
                }
            }
        }

        var clk = false;

        void HalfStep()
        {
            var cpuClk = chip.IsHigh(clk0);

            clk = !clk;

            chip.SetNode(clk_in, clk ? NodeValue.PulledHigh : NodeValue.PulledLow);

            // Only do memory reads / writes if CPU was just clocked and M2 is high.
            if (cpuClk != chip.IsHigh(clk0) && chip.IsHigh(phi2))
            {
                HandleMemoryAccess();
            }

            // Uncomment this line to see chip state at each step.
            //Console.WriteLine($"PC {chip.GetBus(pch):X2}{chip.GetBus(pcl):X2}   X {chip.GetBus(x):X2}   Y {chip.GetBus(y):X2}   A {chip.GetBus(a):X2}   SP {chip.GetBus(s):X2}   AB {chip.GetBus(ab):X4}   DB {chip.GetBus(db):X2}  {(chip.GetNode(rw) == NodeValue.PulledHigh ? 'R' : 'W')}   Phi2 {(chip.GetNode(phi2) == NodeValue.PulledHigh ? '1' : '0')}");
        }

        for (var i = 0; i < 217 * 12; i++)
        {
            HalfStep();
        }

        await Assert.That(output).IsEqualTo("@AABBCC");
    }

    // Based on https://github.com/mist64/perfect6502/blob/268d16647c6b9cb0c6859cae230fd55ad98ff689/apple1basic/apple1basic.c
    [Test]
    public async Task TestApple1Basic()
    {
        var apple1BasicBin = File.ReadAllBytes("2A03/Assets/apple1basic.bin");
        byte[] memory = new byte[ushort.MaxValue + 1];
        Array.Copy(apple1BasicBin, 0, memory, 0xE000, apple1BasicBin.Length);

        memory[0xFFFC] = 0x00;
        memory[0xFFFD] = 0xE0;

        var chip = new Flawless2A03();
        chip.Startup();

        const string stringToPrint = "Hello World";
        var stringIndex = 0;

        var output = "";

        void HandleMemoryAccess()
        {
            if (chip.IsHigh(rw))
            {
                var address = chip.GetBus(ab);

                // 0xD010: Keyboard input register
                // 0xD011: Keyboard control register
                // 0xD012: Display register

                var register = address & 0xFF1F;

                byte data;

                switch (register)
                {
                    case 0xD010:
                        data = (byte)stringToPrint[stringIndex];
                        data |= 0x80;
                        stringIndex++;
                        break;

                    case 0xD011:
                        // If we're still printing the string, then tell CPU we have a character available.
                        data = stringIndex < stringToPrint.Length ? (byte)0x80 : (byte)0;
                        break;

                    case 0xD012:
                        // Tell CPU we're ready to receive a character to the display register.
                        data = 0;
                        break;

                    default:
                        data = memory[address];
                        break;
                }

                chip.SetBus(db, data);
            }
            else
            {
                var address = chip.GetBus(ab);
                var data = chip.GetBus(db);

                var register = address & 0xFF1F;

                switch (register)
                {
                    case 0xD012:
                        var character = (char)(data & 0x7F);
                        output += character;
                        break;

                    default:
                        memory[address] = data;
                        break;
                }
            }
        }

        var clk = false;

        void HalfStep()
        {
            var cpuClk = chip.IsHigh(clk0);

            clk = !clk;

            chip.SetNode(clk_in, clk ? NodeValue.PulledHigh : NodeValue.PulledLow);

            // Only do memory accesses if CPU was just clocked and M2 is high.
            if (cpuClk != chip.IsHigh(clk0) && chip.IsHigh(phi2))
            {
                HandleMemoryAccess();
            }
        }

        for (var i = 0; i < 3000 * 12; i++)
        {
            HalfStep();
        }

        await Assert.That(output).IsEqualTo("\r>Hello World");
    }

    [Test]
    public async Task NesTest()
    {
        byte[] rom;
        using (var reader = new BinaryReader(File.OpenRead("2A03/Assets/nestest.nes")))
        {
            reader.BaseStream.Seek(16, SeekOrigin.Current);
            rom = reader.ReadBytes(16384);
        }

        // Patch the test start address into the RESET vector.
        rom[0x3FFC] = 0x00;
        rom[0x3FFD] = 0xC0;

        var ram = new byte[0x0800];

        // APU and I/O registers - for the purposes of this test, treat them as RAM.
        var apu = new byte[0x18];

        var chip = new Flawless2A03();
        chip.Startup();

        void HandleMemoryAccess()
        {
            if (chip.IsHigh(rw))
            {
                var address = chip.GetBus(ab);

                var data = address switch
                {
                    _ when address <= 0x1FFF => ram[address & 0x07FF],
                    _ when address >= 0x4000 && address <= 0x4017 => apu[address - 0x4000],
                    _ when address >= 0x8000 && address <= 0xFFFF => rom[address - 0x8000 & 0x3FFF],
                    _ => rom[address - 0x4000]
                };

                chip.SetBus(db, data);
            }
            else
            {
                var address = chip.GetBus(ab);
                var data = chip.GetBus(db);

                switch (address)
                {
                    case var _ when address <= 0x1FFF:
                        ram[address & 0x07FF] = data;
                        break;

                    case var _ when address >= 0x4000 && address <= 0x4017:
                        apu[address - 0x4000] = data;
                        break;
                }
            }
        }

        var clk = false;
        var cycle = 0;

        using var writer = new StreamWriter("nestest_trace.log");

        while (true)
        {
            var cpuClk = chip.IsHigh(clk0);

            clk = !clk;

            // TODO: Just for testing.
            if (chip.GetPC() == 0xC5FF)
            {
                // Debug this.
            }

            using (cycle == 627 ? chip.BeginLogging("nestest_transistor_trace.log", c_db4) : null)
            {
                chip.SetNode(clk_in, clk ? NodeValue.PulledHigh : NodeValue.PulledLow);
            }

            if (cycle == 627)
            {
                //break;
            }

            writer.WriteLine(
                "Clock {0}/{1}/{2}   PC {3:X4}   X {4:X2}   Y {5:X2}   A {6:X2}   SP {7:X2}   AB {8:X4}   DB {9:X2}   RW {10}   RES {11}   SYNC {12}",
                chip.IsHigh(clk_in) ? '1' : '0',
                chip.IsHigh(phi2) ? '1' : '0',
                chip.IsHigh(c_clk2out) ? '1' : '0',
                chip.GetPC(),
                chip.GetBus(x),
                chip.GetBus(y),
                chip.GetBus(a),
                chip.GetBus(s),
                chip.GetBus(ab),
                chip.GetBus(db),
                chip.IsHigh(rw) ? '1' : '0',
                chip.IsHigh(res) ? '1' : '0',
                chip.IsHigh(sync) ? '1' : '0');

            // Only do memory accesses if CPU was just clocked and M2 is high.
            if (cpuClk != chip.IsHigh(clk0) && chip.IsHigh(phi2))
            {
                if (chip.GetPC() == 0xC66E)
                {
                    break;
                }

                HandleMemoryAccess();
            }

            cycle++;
        }

        await Assert.That(ram[0x0002]).IsEqualTo((byte)0x000);
        await Assert.That(ram[0x0003]).IsEqualTo((byte)0x000);
    }
}